### ISSUE TITLE
Version Update Discontinuity

### ISSUE THREAD

**Issue by Anyman-Tester** [GalaxyPay/avm-win-node#17]
I just used the current executable installer and the version does not match your latest version release. Also, my Node screen doesn't match your current screenshot and still shows the basic version from 1.1.2.

![Screenshot 2024-11-11 121538](https://github.com/user-attachments/assets/f6bbd94b-8499-4fd0-9ea3-8fe6ec0a9ac5)

**Comment by acfunk** [comment]
The latest setup exe should install version 1.3.0, and it should say that in the window title of the installer. For example `Setup - AvmWinNode version 1.3.0`. What version do you see when looking at Windows Settings > Installed Apps?

Sometimes your browser might cache the old page, can you try refreshing the page?

**Comment by Anyman-Tester** [comment]
When I download AvmWinNode_Setup.exe from the release page the file name is the same. However, I think you fixed the released version because I reinstalled from the most recent file I downloaded and it updated my screen to the latest version.

Awesome work and thanks!

**Comment by acfunk** [comment]
Glad to hear. I was thinking of including the version in the filename. I think I'll do that going forward to avoid confusion.
