### ISSUE TITLE
Where is the Node Token information found? 

### ISSUE THREAD

**Issue by algolinks** [GalaxyPay/avm-win-node#18]
Where can you find the Node Token information for the Galaxy Node?

**Comment by algolinks** [comment]
Can you make this information available on the localhost page someplace?

**Comment by acfunk** [comment]
> Where can you find the Node Token information for the Galaxy Node?

`C:\ProgramData\AvmWinNode\algorand`
OR
`C:\ProgramData\AvmWinNode\voi`

**Comment by acfunk** [comment]
> Can you make this information available on the localhost page someplace?

[v1.3.1](https://github.com/GalaxyPay/avm-win-node/releases/tag/v1.3.1) makes this available

**Comment by acfunk** [comment]
> Can you make this information available on the localhost page someplace?

[v1.3.1](https://github.com/GalaxyPay/avm-win-node/releases/tag/v1.3.1) makes this available
